### ISSUE TITLE
Stitching Drone Images

### ISSUE THREAD

**Issue by Sharathmk99** [Kitware/maptk#228]
Hi,

Sorry for very basic question.
Can i use this tool chain for stitching Drone Images and get GeoTIFF images.

Thanks

**Comment by mleotta** [comment]
Thanks for the question.  MAP-Tk is not (yet) going to handle GeoTIFF generation out of the box, but most of the components are there to make this work.  We can build stitched mosaic images from drone images, but haven't hooked up all the pieces yet to make the results geo-registered an exported to GeoTIFF.  This is something we would like to do but it probably won't happen until we get a volunteer to implement it or someone pays Kitware to add this feature.

**Comment by Sharathmk99** [comment]
Can i get JPEG stitched image from this tool chain?
I can help to implement, but i know only Python language:(

**Comment by mleotta** [comment]
At the moment you can run the "maptk_track_features" tool to get a homography file and then run the [mosaic_images.py](https://github.com/Kitware/maptk/blob/master/scripts/mosaic_images.py) Python script to produce a mosaic image.

You can also run "maptk_bundle_adjust_features" after tracking features to get optimized camera models and an 3D point cloud.  From that you can compute a better ground-plane homography files with the [krtd_and_ply_to_homog.py](https://github.com/Kitware/maptk/blob/master/scripts/krtd_and_ply_to_homog.py) Python script.  Then you run mosaic_images.py as before.
