### ISSUE TITLE
when will v0.10.0 be releaesd

### ISSUE THREAD

**Issue by riddle911** [Kitware/maptk#233]
Hi,mleotta
I found you have already done a gcp tool, which will be in the version 0.10.0.
I am interested in this new function. May I know when will the v0.10 be released?
Appreciate for your work!

**Comment by mleotta** [comment]
Thanks for your interest.  I'm hoping to release 0.10.0 in June.  I've got a few more features I'm trying to wrap up first.

The gcp tool you see is not significantly new functionality.  The current bundle_adjust_tracks tool runs bundle adjustment and already has the capability to read ground control points (GCPs) from a text file and used them to geo-locate the solution after bundle adjustment by fitting a similarity transformation.  The new GCP tool is simply the bundle adjustment tool without the bundle adjustment.  It lets you re-estimate the similarity transformation to adjust geo-location of a previously bundle adjusted solution without needing to re-run bundle adjustment.

In the future it would be good to use GCPs as constraints in the bundle adjustment itself and to provide a GUI tool to select GCPs, but neither of those features will be in the next release.
