### ISSUE TITLE
INS map empty, no output POS files written

### ISSUE THREAD

**Issue by seanfraser** [Kitware/maptk#239]
Hi there,

I have tried running the CLI tools for maptk_track_features and maptk_bundle_adjust on the test data provided from the examples in the CLIF data set. I downloaded and installed the MapTK 0.9.0 binary package and ran the command line tools from that packages bin folder. However when I run the bundle adjust with the same config settings in the examples directory with the metadata included, I still can not get output POS data. For some reason I can't seem to get the output updated POS files and instead only get the krtd files/ landmarks.ply file. I would like to see the updated POS files. The full output after running bundle adjust with the example config settings on the test data is as follows: 

--> st estimation and application - elapsed time: 0.000358 sec
writing output PLY file - elapsed time: 0.000411 sec
2017-07-03 16:53:46.543 INFO bundle_adjust_tracks.cxx(1018): Writing output POS files
WARNING: local geo coordinates do not have an origin
2017-07-03 16:53:46.543 WARN bundle_adjust_tracks.cxx(1033): INS map empty, no output POS files written
--> Writing output POS files - elapsed time: 6.5e-05 sec
2017-07-03 16:53:46.543 INFO bundle_adjust_tracks.cxx(1062): Writing output KRTD files
--> Writing output KRTD files - elapsed time: 0.008628 sec

I was wondering if there was a config setting I was entering incorrectly or something like that.

Thanks a lot!

**Comment by mleotta** [comment]
Which binary package are you using (Windows, Linux, Mac)?  I can try to reproduce this on my end.  Also, we are very close to releasing v0.10.0.  So if something needs to be fixed, we'll probably just fix it for that release.

**Comment by seanfraser** [comment]
I am using the Mac binary packaged on version 0.9.0,

**Comment by mleotta** [comment]
I am unable to reproduce this. Here is what I did:
 1. downloaded the 0.9.0 Mac installer and installed to /Applications
 2. downloaded the kwiver_wami_set_1.tgz example data and extracted it
 3. copied the contents of example configs from the installer into the data directory
  (i.e. copied from `/Applications/MAP-Tk.app/Contents/share/maptk/0.9.0/examples/kwiver_wami_set_1/`)
 4. Ran `maptk_track_features -c maptk_track_features.conf` in the data directory
 5. Ran `maptk_bundle_adjust_tracks -c maptk_bundle_adjust_tracks` in the data directory

I got POS files in the `results/pos` directory and did not see the warning you posted.  Is what you tried different from the above?  Can you capture and post a complete log file?  For example, run `maptk_bundle_adjust_tracks -c maptk_bundle_adjust_tracks > mbat.log 2>&1` and post mbat.log.

**Comment by seanfraser** [comment]
I tried to do exactly as you listed above and it worked with the output pos files. I must have set it up differently or used a different configuration before. I will try to find out based on that the difference between running the above steps how I set it up before. Sorry about that, and thanks for the replies.
