### ISSUE TITLE
maptk_track_features incorrect output

### ISSUE THREAD

**Issue by mmonroe-iai** [Kitware/maptk#259]
I am not sure if this is the correct place to submit this, but I encountered an issue with the maptk_track_features tool and this is how I fixed it. I am using commit 48ea68340fc2e5b79761b62e4491d9a49bed86f6 of the master branch (MAP-Tk 0.10.0).
After running the maptk_track_features tool, the tracks.txt output file only contains the first 2 columns of data (the track ID and the frame ID) and is missing the last 8 columns (the feature data). The maptk_bundle_adjust_tracks tool expects all 10 columns of data to be present in the tracks.txt file. After looking into this issue, line 477 of track_features.cxx calls “kwiver::vital::write_track_file(tracks, output_tracks_file);”, which only writes out the track ID and frame ID to the tracks.txt file, whereas calling “kwiver::vital::write_feature_track_file(tracks, output_tracks_file);” writes out the track ID, frame ID, and feature data. I updated line 477 of track_features.cxx to call “kwiver::vital::write_feature_track_file(tracks, output_tracks_file);” instead. The maptk_track_features tool now produces the correct output.

**Comment by mleotta** [comment]
Good catch.  Thanks!  

It seems I forgot to update that tool to call the correct function after the recent API change in KWIVER that split tracks in feature tracks and object tracks.  Your suggested fix is correct.  If you'd like to make a pull request with your change go ahead.  If you do, please branch off of the `release` branch and make a pull request that targets merging back into `release`.  Ideally you would also make a brief comment in doc/rel_notes/0.10.1 that describes the bug and the fix. (note: you'll need to update to the current `release` (3e3348f3) to find that release notes file). 

If you would rather not make the PR yourself, I will do it.  I just want to give to the opportunity to take credit for the fix in the Git history.

**Comment by mmonroe-iai** [comment]
I don't mind not getting the credit if you would like to do the pull request. Thanks!

**Comment by mleotta** [comment]
I will make the change.

After looking a little closer I need to revise my previous comment that this change should apply to the `release` branch.  It should only apply to `master` because `write_feature_tracks_file` was added after the last releases of KWIVER and MAP-Tk.
