### ISSUE TITLE
How to prepare test data?

### ISSUE THREAD

**Issue by qingyezeng** [Kitware/maptk#36]
I have built maptk successfully, but when I tried on s sequence of aerial images, failed to get result. So how to prepare the test data? or do you have sample data to share? Thanks!

**Comment by mleotta** [comment]
Thanks for your interest in MAP-Tk.  Unfortunately, I don't have an sample data that is easily sharable.  One option is the [CLIF2007](https://www.sdms.afrl.af.mil/index.php?collection=clif2007) data set that you can download.  We've processed subsets of that with MAP-Tk.

In terms of preparing the data, there are a couple of things to note:

1. The core of MAP-Tk by itself doesn't do much, you need to compile some of the other modules too.  In the current version, you'll probably need OpenCV, VXL, and PROJ4 to run the whole pipeline.
2. Currently we only support lists of images (not video files), so you'll need a sequence of images.
3. Examples of default/recommended configuration files can be found in the tools/config directory
4. You'll want to run maptk_track_features first to get feature tracks followed by maptk_bundle_adjust_tracks to optimize the cameras and 3D points.

Please keep in mind that this software is still in early stages of development and is not yet as full featured as some other tools out there.  You'll need to specify you camera intrinsics in the config file, radial distortion models are not yet supported, camera pose initialization if very sub-optimal, etc.  We are working on all of things and more, but they will take time.  If you'd like to help us improve the software, we are looking for contributors, and if you have further specific questions, please ask.

**Comment by qingyezeng** [comment]
Thanks, Matt. I will give it a try on the dataset, and feedback later. Also I would like to help for improving maptk. The target of maptk is interesting.

**Comment by mleotta** [comment]
FYI, CLIF2007 is very large and consists of multiple cameras.  We've focused on a few hundred frames from just one camera.

Also, please note that there are big restructuring changes coming to the MAP-Tk code base, likely in about a month.  These changes are pending public release review by our Air Force sponsor.  Running the tools should remain about the same after the changes, but the code is being significantly reorganized into a true dynamic plugin framework and we are shifting to Eigen3 for matrix operations.
